import sqlite3 from 'sqlite3';

const databaseName = 'toyprj1';
const database = new sqlite3.Database(`./${databaseName}.db`);

database.serialize(() => {
  database.run(`
    CREATE TABLE IF NOT EXISTS USER(
      USER_SERIAL_NUMBER TEXT PRIMARY KEY,
      USER_ID TEXT NOT NULL,
      USER_PW TEXT NOT NULL,
      USER_GRADE INTEGER NOT NULL,
      USER_NAME TEXT,
      USER_PHONE_NUMBER TEXT,
      USER_EMAIL TEXT,
      USER_RANK TEXT,
      USER_IMAGE BLOB
    )`).run(`
    CREATE TABLE IF NOT EXISTS WORK(
      WORK_SERIAL_NUMBER TEXT PRIMARY KEY,
      WORK_DATE TEXT NOT NULL,
      WORK_START_DATE_TIME TEXT,
      WORK_END_DATE_TIME TEXT,
      FOREIGN KEY(WORK_SERIAL_NUMBER) REFERENCES USER(USER_SERIAL_NUMBER)
    )`).run(`
    CREATE TABLE IF NOT EXISTS ABSENCE(
      ABSENCE_SERIAL_NUMBER TEXT PRIMARY KEY,
      ABSENCE_TYPE TEXT NOT NULL,
      ABSENCE_START_DATE_TIME TEXT NOT NULL,
      ABSENCE_END_DATE_TIME TEXT NOT NULL,
      ABSENCE_DETAIL_CONTENT TEXT,
      FOREIGN KEY(ABSENCE_SERIAL_NUMBER) REFERENCES USER(USER_SERIAL_NUMBER)
    )`).run(`
    CREATE TABLE IF NOT EXISTS NOTICE(
      NOTICE_SERIAL_NUMBER TEXT PRIMARY KEY,
      NOTICE_TITLE TEXT NOT NULL,
      NOTICE_CONTENT TEXT NOT NULL,
      NOTICE_IMAGE BLOB,
      NOTICE_DATE_TIME TEXT
    )`);
});

export default database;
